export const ActionTypes = {
  SET_FACE_PRODUCTS: "SET_FACE_PRODUCTS",
  SET_LIPS_PRODUCTS: "SET_LIPS_PRODUCTS",
  SET_EYES_PRODUCTS: "SET_EYES_PRODUCTS",
  SET_CHEEKS_PRODUCTS: "SET_CHEEKS_PRODUCTS",
  SET_PALETTS_PRODUCTS: "SET_PALETTS_PRODUCTS",
  SET_VEGAN_PRODUCTS: "SET_VEGAN_PRODUCTS",
  SET_BRUSHES_PRODUCTS: "SET_BRUSHES_PRODUCTS",
  SET_NAIL_PRODUCTS: "SET_NAIL_PRODUCTS",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  SET_CART_ITEMS_NUMBERS: "SET_CART_ITEMS_NUMBERS",
  SET_DELETE_CART_ITEM: "SET_DELETE_CART_ITEM",
};
